# Archivo para configurar MongoDB con Docker Compose
# Uso: docker-compose up -d

version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-ecommerce
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ecommerce

volumes:
  mongodb-data:
    driver: local
